newmenu:
  New: new

submenu:
  Keywords: keywords

customize:
    logo:
        enabled: false
        width: 40
        height: 40
        url: 
    highlight: monokai
    sidebar: 
    category_perExpand: false 
    thumbnail: false
    favicon: 
    default_index_file: 
    social_links:
        github: 
        stack-overflow: 
        codepen: 
        rss:
    social_link_tooltip: false

widgets: 

auto_excerpt:
    enable: true
    lines: 1

search:
    insight: false 
    swiftype: 
    baidu: false 

history_control: 
    enable: true
    server_link: ""
    user: 
    repertory: 
    branch: 

# Plugins
plugins:
    lightgallery: false
    justifiedgallery: false
    mathjax: false
    google_analytics: 
    google_site_verification: 
    baidu_analytics: 
    busuanzi_count: false

miscellaneous:
    open_graph: 
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus: