name: Generate Site

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  repository_dispatch:
    types: [content-updated]
  push:
    branches:
      - main
    paths:
      - 'site/**'

permissions: write-all

jobs:
  build:
    uses: wikip-co/content/.github/workflows/hexo-deploy.yml@main
    with:
      site_name: wikip.co
      branch: main
      enable_docker: true
      enable_encryption: false
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
      EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
